/**:
  ros__parameters:
    # 52S-CF0 - VMB
    # lat: 36.12491471
    # lon: 126.77473954
    # alt: 84.0
    # yaw_offset_deg: 0.0
    # 52S-CF60 - VMB
    origin_lat: 36.7292921
    origin_lon: 127.4429577
    origin_alt: 84.0
    yaw_offset_deg: 0.0

    utm_origin_easting: 360965.99
    utm_origin_northing: 4065972.49
    utm_origin_alt: 84.0

    rotate_latlon_xy_by_yaw_offset: true
