#!/usr/bin/env bash
# Bluetooth Audio Amplifier Board Service Setup Script
# Usage: sudo ./setup_bt_audio.sh <BT_MAC_ADDRESS> [DEVICE_NAME]
# Example: sudo ./setup_bt_audio.sh AA:BB:CC:DD:EE:FF "MyAmpBoard"

set -euo pipefail

# ── 색상 출력 ─────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── 파라미터 검증 ─────────────────────────────────────────────────────────────
if [[ $# -lt 1 ]]; then
    error "사용법: sudo $0 <블루투스_MAC_주소> [장치_이름]"
    error "예시:   sudo $0 AA:BB:CC:DD:EE:FF \"MyAmpBoard\""
    exit 1
fi

BT_MAC="${1^^}"   # 대문자로 정규화
DEVICE_NAME="${2:-bt_amp_$(echo "$BT_MAC" | tr ':' '_')}"

# MAC 주소 형식 검증 (XX:XX:XX:XX:XX:XX)
if ! [[ "$BT_MAC" =~ ^([0-9A-F]{2}:){5}[0-9A-F]{2}$ ]]; then
    error "잘못된 MAC 주소 형식: $BT_MAC"
    error "올바른 형식: AA:BB:CC:DD:EE:FF"
    exit 1
fi

# HH_260728 - DEVICE_NAME is embedded in generated shell/systemd text. Keep it
# human-readable but reject shell metacharacters, quotes, and control characters.
if ! [[ "$DEVICE_NAME" =~ ^[A-Za-z0-9._\ -]{1,64}$ ]]; then
    error "장치 이름은 영문/숫자/공백/._- 문자만 1~64자로 사용할 수 있습니다."
    exit 1
fi

BT_MAC_ESCAPED="${BT_MAC//:/_}"          # 서비스 파일명용 (콜론 → 언더스코어)
SERVICE_NAME="bt-audio-${BT_MAC_ESCAPED}"
CONNECT_SCRIPT="/usr/local/bin/bt_audio_connect_${BT_MAC_ESCAPED}.sh"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

info "블루투스 오디오 앰프 서비스 등록 시작"
info "MAC 주소  : $BT_MAC"
info "장치 이름 : $DEVICE_NAME"
info "서비스명  : $SERVICE_NAME"

# ── 의존 패키지 확인 ─────────────────────────────────────────────────────────
check_deps() {
    local missing=()
    for cmd in bluetoothctl; do
        command -v "$cmd" &>/dev/null || missing+=("$cmd")
    done

    # 오디오 백엔드 감지
    if command -v pw-cli &>/dev/null; then
        AUDIO_BACKEND="pipewire"
        info "오디오 백엔드: PipeWire 감지됨"
        # HH_260728 - PipeWire routing below uses wpctl, not pw-cli. Refuse
        # provisioning before any system file is written when wpctl is absent.
        command -v wpctl &>/dev/null || missing+=("wpctl")
    elif command -v pactl &>/dev/null; then
        AUDIO_BACKEND="pulseaudio"
        info "오디오 백엔드: PulseAudio 감지됨"
    elif command -v bluealsa-aplay &>/dev/null; then
        AUDIO_BACKEND="bluealsa"
        info "오디오 백엔드: BlueALSA 감지됨"
    else
        warn "오디오 백엔드를 감지하지 못했습니다. PulseAudio/PipeWire/BlueALSA 중 하나를 설치하세요."
        AUDIO_BACKEND="generic"
    fi

    if [[ ${#missing[@]} -gt 0 ]]; then
        error "필수 명령이 없습니다: ${missing[*]}"
        for missing_cmd in "${missing[@]}"; do
            case "$missing_cmd" in
                bluetoothctl) error "bluetoothctl 설치: sudo apt install bluez" ;;
                wpctl) error "wpctl을 제공하는 WirePlumber 패키지를 설치하세요." ;;
            esac
        done
        exit 1
    fi
}

check_deps

# HH_260728 - Provisioning is only valid for an explicitly paired target. Check
# this before root-only file creation so a typo or unpaired MAC cannot leave a
# reconnect service or script behind.
verify_paired_device() {
    local device_info
    if ! device_info="$(bluetoothctl info "$BT_MAC" 2>/dev/null)"; then
        error "블루투스 장치 정보를 찾을 수 없습니다: $BT_MAC"
        error "먼저 bluetoothctl에서 장치를 검색하고 페어링하세요."
        exit 1
    fi
    if ! grep -Eq '^[[:space:]]*Paired:[[:space:]]+yes[[:space:]]*$' <<< "$device_info"; then
        error "장치가 페어링되지 않았습니다: $BT_MAC"
        error "먼저 실행: bluetoothctl pair $BT_MAC"
        exit 1
    fi
    info "페어링 확인 완료: $BT_MAC"
}

verify_paired_device

# root 권한 확인 — 읽기 전용 의존성/페어링 검증을 모두 통과한 뒤 확인한다.
if [[ $EUID -ne 0 ]]; then
    error "이 스크립트는 root 권한으로 실행해야 합니다."
    error "다시 실행: sudo $0 $BT_MAC"
    exit 1
fi

# HH_260728 - Render both per-MAC files first, validate every existing target,
# then install. Identical reruns are idempotent; differing files are never
# overwritten implicitly.
RENDER_DIR="$(mktemp -d -t camrod-bt-audio.XXXXXX)"
trap 'rm -rf -- "$RENDER_DIR"' EXIT
CONNECT_SCRIPT_CANDIDATE="${RENDER_DIR}/connect.sh"
SERVICE_FILE_CANDIDATE="${RENDER_DIR}/${SERVICE_NAME}.service"

# ── 연결 스크립트 생성 ────────────────────────────────────────────────────────
info "연결 스크립트 준비 중: $CONNECT_SCRIPT"

cat > "$CONNECT_SCRIPT_CANDIDATE" << SCRIPT_EOF
#!/usr/bin/env bash
# Auto-generated by setup_bt_audio.sh
# Bluetooth Audio Connect: $DEVICE_NAME ($BT_MAC)

BT_MAC="$BT_MAC"
DEVICE_NAME="$DEVICE_NAME"
AUDIO_BACKEND="$AUDIO_BACKEND"
MAX_RETRY=10
RETRY_INTERVAL=5

log() { logger -t "bt-audio[$DEVICE_NAME]" "\$*"; echo "\$(date '+%F %T') \$*"; }

wait_bluetooth_ready() {
    local count=0
    while ! bluetoothctl show | grep -q "Powered: yes"; do
        log "블루투스 어댑터 대기 중... (\$count/30)"
        sleep 2
        (( count++ ))
        [[ \$count -ge 30 ]] && { log "블루투스 어댑터 시작 실패"; exit 1; }
    done
    log "블루투스 어댑터 준비 완료"
}

connect_device() {
    local attempt=0
    while [[ \$attempt -lt \$MAX_RETRY ]]; do
        log "연결 시도 \$(( attempt + 1 )) / \$MAX_RETRY : \$BT_MAC"

        # 이미 연결되어 있으면 종료
        if bluetoothctl info "\$BT_MAC" 2>/dev/null | grep -q "Connected: yes"; then
            log "이미 연결됨: \$DEVICE_NAME"
            return 0
        fi

        # 페어링 여부 확인
        if ! bluetoothctl info "\$BT_MAC" 2>/dev/null | grep -q "Paired: yes"; then
            log "장치가 페어링되지 않았습니다. 먼저 페어링하세요: bluetoothctl pair \$BT_MAC"
            sleep "\$RETRY_INTERVAL"
            (( attempt++ ))
            continue
        fi

        # 신뢰 설정 (부팅 시 자동 연결 허용)
        bluetoothctl trust "\$BT_MAC" 2>/dev/null || true

        # 연결 시도
        if bluetoothctl connect "\$BT_MAC" 2>/dev/null; then
            sleep 2
            if bluetoothctl info "\$BT_MAC" 2>/dev/null | grep -q "Connected: yes"; then
                log "연결 성공: \$DEVICE_NAME (\$BT_MAC)"
                setup_audio_routing
                return 0
            fi
        fi

        log "연결 실패, \${RETRY_INTERVAL}초 후 재시도..."
        sleep "\$RETRY_INTERVAL"
        (( attempt++ ))
    done

    log "최대 재시도 횟수 초과. 연결 실패: \$BT_MAC"
    return 1
}

setup_audio_routing() {
    log "오디오 라우팅 설정 중 (백엔드: \$AUDIO_BACKEND)"
    sleep 2

    case "\$AUDIO_BACKEND" in
        pipewire)
            # PipeWire: 블루투스 장치를 기본 오디오 싱크로 설정
            local sink
            sink=\$(pw-cli ls Node 2>/dev/null \
                | grep -i "bluez_output\|bluetooth" \
                | grep -i "$(echo "$BT_MAC" | tr ':' '_')\|$(echo "$BT_MAC" | tr ':' '.')" \
                | head -1 | awk '{print \$2}' | tr -d ',')
            if [[ -n "\$sink" ]]; then
                log "PipeWire 싱크 설정: \$sink"
                wpctl set-default "\$sink" 2>/dev/null || true
            else
                log "PipeWire 블루투스 싱크를 찾지 못함 (자동 라우팅 대기)"
            fi
            ;;
        pulseaudio)
            # PulseAudio: 블루투스 장치를 기본 싱크로 설정
            local sink
            sink=\$(pactl list short sinks 2>/dev/null \
                | grep -i "bluez\|bluetooth" \
                | grep -i "$(echo "$BT_MAC" | tr ':' '_')" \
                | head -1 | awk '{print \$1}')
            if [[ -n "\$sink" ]]; then
                log "PulseAudio 기본 싱크 설정: \$sink"
                pactl set-default-sink "\$sink" 2>/dev/null || true
            else
                log "PulseAudio 블루투스 싱크를 찾지 못함"
            fi
            ;;
        bluealsa)
            log "BlueALSA 모드: ALSA 라우팅은 /etc/asound.conf 에서 설정"
            ;;
        *)
            log "오디오 백엔드 불명. 수동으로 라우팅을 설정하세요."
            ;;
    esac
}

monitor_connection() {
    log "연결 모니터링 시작 (장치: \$DEVICE_NAME)"
    while true; do
        sleep 30
        if ! bluetoothctl info "\$BT_MAC" 2>/dev/null | grep -q "Connected: yes"; then
            log "연결 끊김 감지. 재연결 시도..."
            connect_device || log "재연결 실패. 다음 주기에 재시도"
        fi
    done
}

# ── 메인 ──────────────────────────────────────────────────────────────────────
wait_bluetooth_ready
connect_device
monitor_connection
SCRIPT_EOF

# ── systemd 서비스 파일 생성 ──────────────────────────────────────────────────
info "systemd 서비스 파일 준비 중: $SERVICE_FILE"

cat > "$SERVICE_FILE_CANDIDATE" << SERVICE_EOF
[Unit]
Description=Bluetooth Audio Amplifier - ${DEVICE_NAME} (${BT_MAC})
Documentation=https://wiki.archlinux.org/title/Bluetooth
After=bluetooth.target sound.target network.target
Wants=bluetooth.target
# BlueALSA 사용 시 아래 주석 해제
# After=bluealsa.service

[Service]
Type=simple
ExecStart=${CONNECT_SCRIPT}
Restart=on-failure
RestartSec=10
# 시작 전 블루투스 어댑터 전원 ON 보장
ExecStartPre=/usr/bin/bluetoothctl power on
# 서비스 중지 시 연결 해제
ExecStop=/usr/bin/bluetoothctl disconnect ${BT_MAC}
TimeoutStartSec=60
TimeoutStopSec=10

# 보안 강화 (필요 시 조정)
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=yes
ReadWritePaths=/run /tmp /var/log

# 로그
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}

[Install]
WantedBy=multi-user.target
SERVICE_EOF

validate_existing_target() {
    local candidate="$1"
    local target="$2"
    local label="$3"

    if [[ -L "$target" ]]; then
        error "${label} 대상이 심볼릭 링크입니다. 안전을 위해 중단합니다: $target"
        return 1
    fi
    if [[ -e "$target" && ! -f "$target" ]]; then
        error "${label} 대상이 일반 파일이 아닙니다. 안전을 위해 중단합니다: $target"
        return 1
    fi
    if [[ -f "$target" ]] && ! cmp -s "$candidate" "$target"; then
        error "기존 ${label} 내용이 현재 설정과 다릅니다. 묵시적으로 덮어쓰지 않습니다: $target"
        error "기존 파일을 검토·백업한 뒤 명시적으로 제거하고 다시 실행하세요."
        return 1
    fi
}

install_if_missing() {
    local candidate="$1"
    local target="$2"
    local mode="$3"
    local label="$4"

    if [[ -f "$target" ]]; then
        info "동일한 ${label} 유지: $target"
        return 0
    fi
    install -m "$mode" "$candidate" "$target"
    info "${label} 생성 완료: $target"
}

# 한 대상이라도 충돌하면 다른 대상도 쓰기 전에 종료한다.
validate_existing_target "$CONNECT_SCRIPT_CANDIDATE" "$CONNECT_SCRIPT" "연결 스크립트"
validate_existing_target "$SERVICE_FILE_CANDIDATE" "$SERVICE_FILE" "서비스 파일"
install_if_missing "$CONNECT_SCRIPT_CANDIDATE" "$CONNECT_SCRIPT" 0755 "연결 스크립트"
install_if_missing "$SERVICE_FILE_CANDIDATE" "$SERVICE_FILE" 0644 "서비스 파일"

# ── BlueALSA용 ALSA 설정 (선택적) ───────────────────────────────────────────
if [[ "$AUDIO_BACKEND" == "bluealsa" ]]; then
    ASOUND_CONF="/etc/asound.conf"
    if [[ ! -f "$ASOUND_CONF" ]]; then
        info "BlueALSA ALSA 설정 파일 생성: $ASOUND_CONF"
        cat > "$ASOUND_CONF" << ALSA_EOF
# BlueALSA 블루투스 오디오 설정 (${DEVICE_NAME})
defaults.bluealsa.service  "org.bluealsa"
defaults.bluealsa.device   "${BT_MAC}"
defaults.bluealsa.profile  "a2dp"
defaults.bluealsa.delay    10000

pcm.!default {
    type plug
    slave.pcm {
        type bluealsa
        device "${BT_MAC}"
        profile "a2dp"
    }
}

ctl.!default {
    type bluealsa
}
ALSA_EOF
        info "ALSA 설정 완료 (/etc/asound.conf)"
    else
        warn "/etc/asound.conf 이 이미 존재합니다. 수동으로 BlueALSA 설정을 추가하세요."
    fi
fi

# ── 서비스 등록 및 활성화 ─────────────────────────────────────────────────────
info "systemd 데몬 리로드 중..."
systemctl daemon-reload

info "서비스 활성화 중 (부팅 시 자동 시작)..."
systemctl enable "${SERVICE_NAME}.service"

echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  블루투스 오디오 서비스 등록 완료!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo ""
echo "  장치 이름 : $DEVICE_NAME"
echo "  MAC 주소  : $BT_MAC"
echo "  서비스명  : $SERVICE_NAME"
echo "  백엔드    : $AUDIO_BACKEND"
echo ""
echo "  [ 유용한 명령어 ]"
echo "  서비스 시작    : sudo systemctl start ${SERVICE_NAME}"
echo "  서비스 중지    : sudo systemctl stop ${SERVICE_NAME}"
echo "  서비스 재시작  : sudo systemctl restart ${SERVICE_NAME}"
echo "  상태 확인      : sudo systemctl status ${SERVICE_NAME}"
echo "  로그 보기      : journalctl -u ${SERVICE_NAME} -f"
echo "  서비스 비활성화: sudo systemctl disable ${SERVICE_NAME}"
echo ""

# 지금 바로 시작 여부 확인
read -r -p "지금 바로 서비스를 시작하시겠습니까? [y/N] " START_NOW
if [[ "${START_NOW,,}" == "y" ]]; then
    # 먼저 페어링 확인
    if bluetoothctl info "$BT_MAC" 2>/dev/null | grep -q "Paired: yes"; then
        info "서비스 시작 중..."
        systemctl start "${SERVICE_NAME}.service"
        sleep 3
        systemctl status "${SERVICE_NAME}.service" --no-pager || true
    else
        warn "장치가 아직 페어링되지 않았습니다."
        warn "먼저 페어링을 완료한 후 서비스를 시작하세요:"
        warn "  sudo bluetoothctl"
        warn "  [bluetooth]# scan on"
        warn "  [bluetooth]# pair $BT_MAC"
        warn "  [bluetooth]# trust $BT_MAC"
        warn "  [bluetooth]# exit"
        warn "  sudo systemctl start ${SERVICE_NAME}"
    fi
else
    info "나중에 'sudo systemctl start ${SERVICE_NAME}' 으로 시작할 수 있습니다."
fi
