<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_map_checkers_bringup</name>
  <version>0.0.0</version>
  <description>Bringup launch for map diagnostic checker nodes (Lanelet CostGrid)</description>
  <maintainer email="avg@todo.todo">avg</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_map_cost_grid_checker</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
