drop_zones:
  - id: "dz_way_2048"
    type: "drop_zone"
    source: "osm_area"
    x: -15.2741
    y: -2.94276
    z: -2.17912
    yaw_deg: -179.669
    corners:
      - x: -17.6794
        y: -1.4103
        z: -2.3119
      - x: -12.9367
        y: -1.3895
        z: -2.0102
      - x: -12.8069
        y: -4.4651
        z: -1.9666
      - x: -17.6401
        y: -4.493
        z: -2.2982
      - x: -17.7095
        y: -1.4348
        z: -2.3087
  - id: "dz_way_2054"
    type: "drop_zone"
    source: "osm_area"
    x: 43.7385
    y: -7.62852
    z: -2.17912
    yaw_deg: 158.397
    corners:
      - x: 46.8999
        y: -6.3622
        z: -2.3119
      - x: 45.1274
        y: -10.7624
        z: -2.0102
      - x: 40.567
        y: -8.9565
        z: -1.9666
      - x: 42.3665
        y: -4.4705
        z: -2.2982
      - x: 46.8873
        y: -6.3245
        z: -2.3087
