<?xml version="1.0"?>
<package format="3">
  <name>camrod_api</name>
  <version>0.0.1</version>
  <description>API bridge and UI backend package for CAMROD runtime control.</description>
  <maintainer email="hwanhong57@gmail.com">hong</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>diagnostic_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
