<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_localization_mode_checker</name>
  <version>0.0.0</version>
  <description>Localization mode/confidence/sensor health diagnostics checker (AvgLocalizationStatus)</description>
  <maintainer email="avg@todo.todo">avg</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>avg_msgs</depend>
  <depend>diagnostic_msgs</depend>
  <depend>diagnostic_updater</depend>
  <depend>robot_diagnostics_base</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
