ARG BASE_IMAGE=camrod/base:humble
FROM ${BASE_IMAGE}

ARG MODULE=camrod_bringup
ARG ROS_DISTRO=humble

SHELL ["/bin/bash", "-lc"]
WORKDIR /workspaces/camrod_ws

COPY . /workspaces/camrod_ws/src

RUN source /opt/ros/${ROS_DISTRO}/setup.bash && \
    rosdep install --from-paths src --ignore-src -r -y || true

RUN source /opt/ros/${ROS_DISTRO}/setup.bash && \
    colcon build --symlink-install --packages-up-to ${MODULE}

CMD ["bash"]
