#!/usr/bin/env python3
"""
Generate module parameter contracts from source declarations and YAML bindings.

Output:
  - Markdown report describing:
    - node -> declared parameters (from C++ / Python)
    - YAML keys -> parameter keys (from config/**/*.yaml)
    - quick coverage hints

Usage:
  python3 util/generate_module_param_contract.py
  python3 util/generate_module_param_contract.py --root /home/hong/camrod_ws/src
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Set, Tuple

import yaml


CPP_NODE_RE = re.compile(r'(?:rclcpp::)?Node\(\s*"([^"]+)"\s*\)')
CPP_DECLARE_RE = re.compile(
    r'declare_parameter(?:<[^>]+>)?\(\s*"([^"]+)"\s*(?:,|\))'
)
PY_NODE_RE = re.compile(r"super\(\)\.__init__\(\s*['\"]([^'\"]+)['\"]\s*\)")
PY_DECLARE_RE = re.compile(r"declare_parameter\(\s*['\"]([^'\"]+)['\"]\s*,")


@dataclass
class NodeContract:
    node_name: str
    source_file: str
    declared_params: Set[str] = field(default_factory=set)


def iter_module_dirs(root: Path) -> List[Path]:
    return sorted(
        p for p in root.iterdir()
        if p.is_dir() and p.name.startswith("camrod_")
    )


def collect_cpp_contracts(module_dir: Path) -> List[NodeContract]:
    contracts: List[NodeContract] = []
    for src in sorted(module_dir.rglob("*.cpp")):
        if "/external/" in src.as_posix():
            continue
        text = src.read_text(encoding="utf-8", errors="ignore")
        node_matches = CPP_NODE_RE.findall(text)
        param_matches = CPP_DECLARE_RE.findall(text)
        if not node_matches and not param_matches:
            continue
        node_name = node_matches[0] if node_matches else src.stem
        c = NodeContract(
            node_name=node_name,
            source_file=str(src.relative_to(module_dir)),
            declared_params=set(param_matches),
        )
        contracts.append(c)
    return contracts


def collect_py_contracts(module_dir: Path) -> List[NodeContract]:
    contracts: List[NodeContract] = []
    for src in sorted(module_dir.rglob("*.py")):
        if "/external/" in src.as_posix():
            continue
        if "__pycache__" in src.parts:
            continue
        text = src.read_text(encoding="utf-8", errors="ignore")
        node_matches = PY_NODE_RE.findall(text)
        param_matches = PY_DECLARE_RE.findall(text)
        if not node_matches and not param_matches:
            continue
        node_name = node_matches[0] if node_matches else src.stem
        c = NodeContract(
            node_name=node_name,
            source_file=str(src.relative_to(module_dir)),
            declared_params=set(param_matches),
        )
        contracts.append(c)
    return contracts


def collect_yaml_params(module_dir: Path) -> Dict[str, Set[str]]:
    """
    Return map:
      yaml node key (e.g. /sensing/lidar_preprocessor) -> params
    """
    out: Dict[str, Set[str]] = {}
    cfg_dir = module_dir / "config"
    if not cfg_dir.exists():
        return out

    for y in sorted(cfg_dir.rglob("*.yaml")):
        try:
            doc = yaml.safe_load(y.read_text(encoding="utf-8"))
        except Exception:
            continue
        if not isinstance(doc, dict):
            continue
        for top_key, top_val in doc.items():
            if not isinstance(top_val, dict):
                continue
            ros_params = top_val.get("ros__parameters")
            if not isinstance(ros_params, dict):
                continue
            key = f"{top_key} @ {y.relative_to(module_dir)}"
            out[key] = set(str(k) for k in ros_params.keys())
    return out


def score_yaml_match(
    node_name: str, declared: Set[str], yaml_items: Dict[str, Set[str]]
) -> List[Tuple[str, int, int, int]]:
    """
    Return candidate YAML matches:
      (yaml_key, intersect, missing, extra)
    """
    rows: List[Tuple[str, int, int, int]] = []
    for yk, yp in yaml_items.items():
        node_key = yk.split(" @ ", 1)[0]
        if node_name not in node_key and node_key.rsplit("/", 1)[-1] != node_name:
            continue
        inter = len(declared & yp)
        missing = len(declared - yp)
        extra = len(yp - declared)
        rows.append((yk, inter, missing, extra))
    rows.sort(key=lambda r: (-r[1], r[2], r[3], r[0]))
    return rows


def generate_markdown(root: Path) -> str:
    lines: List[str] = []
    lines.append("# Module Parameter Contract (Code-First)")
    lines.append("")
    lines.append("Generated by `util/generate_module_param_contract.py`.")
    lines.append("")

    for module in iter_module_dirs(root):
        cpp_contracts = collect_cpp_contracts(module)
        py_contracts = collect_py_contracts(module)
        yaml_params = collect_yaml_params(module)
        all_contracts = cpp_contracts + py_contracts

        lines.append(f"## {module.name}")
        lines.append("")
        lines.append(f"- Nodes scanned: {len(all_contracts)}")
        lines.append(f"- YAML blocks scanned: {len(yaml_params)}")
        lines.append("")

        if not all_contracts:
            lines.append("_No node contracts found._")
            lines.append("")
            continue

        for c in sorted(all_contracts, key=lambda x: x.node_name):
            lines.append(f"### Node `{c.node_name}`")
            lines.append(f"- Source: `{c.source_file}`")
            lines.append(f"- Declared params: {len(c.declared_params)}")

            if c.declared_params:
                lines.append("- Params:")
                for p in sorted(c.declared_params):
                    lines.append(f"  - `{p}`")
            else:
                lines.append("- Params: _(none)_")

            candidates = score_yaml_match(c.node_name, c.declared_params, yaml_params)
            if candidates:
                lines.append("- YAML candidates:")
                for yk, inter, missing, extra in candidates[:3]:
                    lines.append(
                        f"  - `{yk}`: overlap={inter}, missing={missing}, extra={extra}"
                    )
            else:
                lines.append("- YAML candidates: _(none)_")
            lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--root",
        type=str,
        default=str(Path(__file__).resolve().parents[1]),
        help="Workspace src root containing camrod_* packages.",
    )
    parser.add_argument(
        "--out",
        type=str,
        default="TODO_MODULE_PARAM_CONTRACT.md",
        help="Output markdown path (relative to root if not absolute).",
    )
    args = parser.parse_args()

    root = Path(args.root).resolve()
    out = Path(args.out)
    if not out.is_absolute():
        out = root / out

    md = generate_markdown(root)
    out.write_text(md, encoding="utf-8")
    print(f"Wrote: {out}")


if __name__ == "__main__":
    main()
