camping_sites:
  - id: "dz_area_1353"
    type: "camping_site_1"
    source: "area"
    x: 26.7449
    y: -5.5304
    z: -291.542
    yaw_deg: 23.745
  - id: "dz_area_1281"
    type: "camping_site_2"
    source: "area"
    x: 18.0335
    y: -7.74761
    z: -291.803
    yaw_deg: -66.1578
  - id: "dz_area_1341"
    type: "camping_site_3"
    source: "area"
    x: 24.2255
    y: -0.0389968
    z: -291.6
    yaw_deg: -66.2706
  - id: "dz_area_1272"
    type: "camping_site_4"
    source: "area"
    x: 14.9887
    y: -0.658465
    z: -291.953
    yaw_deg: -67.9123
  - id: "dz_area_1329"
    type: "camping_site_5"
    source: "area"
    x: 21.8068
    y: 5.46011
    z: -291.737
    yaw_deg: 21.9274
  - id: "dz_area_1263"
    type: "camping_site_6"
    source: "area"
    x: 12.549
    y: 5.06773
    z: -292.01
    yaw_deg: 113.262
  - id: "dz_area_1317"
    type: "camping_site_7"
    source: "area"
    x: 19.5216
    y: 10.7058
    z: -291.764
    yaw_deg: 20.5798
  - id: "dz_area_1254"
    type: "camping_site_8"
    source: "area"
    x: 10.0267
    y: 11.3076
    z: -292.085
    yaw_deg: 111.259
  - id: "dz_area_1305"
    type: "camping_site_9"
    source: "area"
    x: 17.2349
    y: 16.5345
    z: -291.939
    yaw_deg: -169.793
  - id: "dz_area_1245"
    type: "camping_site_10"
    source: "area"
    x: 7.65649
    y: 17.2487
    z: -292.395
    yaw_deg: 111.253
  - id: "dz_area_1293"
    type: "camping_site_11"
    source: "area"
    x: 15.6604
    y: 21.5376
    z: -292.239
    yaw_deg: 5.68398
  - id: "dz_area_1233"
    type: "camping_site_12"
    source: "area"
    x: 5.49196
    y: 22.8861
    z: -292.607
    yaw_deg: -69.309
  - id: "dz_area_1219"
    type: "camping_site_13"
    source: "area"
    x: -0.877043
    y: 28.6995
    z: -292.785
    yaw_deg: 110.876
