<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_planning_checkers_bringup</name>
  <version>0.0.0</version>
  <description>Bringup launch for planning diagnostic checker nodes (Lifecycle/Costmap/NavStatus/Path)</description>
  <maintainer email="avg@todo.todo">avg</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_planning_lifecycle_checker</exec_depend>
  <exec_depend>robot_planning_costmap_checker</exec_depend>
  <exec_depend>robot_planning_nav_status_checker</exec_depend>
  <exec_depend>robot_planning_path_checker</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
