/**:
  ros__parameters:
    host: www.gnssdata.or.kr
    port: 2101
    mountpoint: CNJU-RTCM31
    authenticate: true
    username: hwanhong57@gmail.com
    password: gnss

    # Force rtcm_msgs (avoid mavros_msgs dependency)
    rtcm_message_package: rtcm_msgs

    # Ensure topic name (some versions use 'rtcm_topic')
    rtcm_topic: /rtcm
    
    ntrip_version: "None"
    ssl: false
    cert: "None"
    key: "None"
    ca_cert: "None"

    rtcm_frame_id: "gps"
    rtcm_timeout_seconds: 4
    reconnect_attempt_max: 10
    reconnect_attempt_wait_seconds: 5
