apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.120
    max_hamming: 0
    profile: false

    detector:
      threads: 2
      decimate: 2.0
      blur: 0.0
      refine: 1
      sharpening: 0.25
      debug: 0

    tag:
      ids: [0]
      frames: ["dock_tag"]
      sizes: [0.120]
