<?xml version="1.0"?>
<package format="3">
  <name>camrod_docking</name>
  <version>0.0.1</version>
  <description>Docking package for autonomous dock approach using AprilTag detection</description>

  <maintainer email="you@todo.com">you</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>isaac_ros_apriltag_interfaces</depend>
  <depend>avg_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>opennav_docking_msgs</depend>
  <exec_depend>opennav_docking</exec_depend>
  <exec_depend>opennav_docking_core</exec_depend>
  <exec_depend>isaac_ros_apriltag</exec_depend>
  <exec_depend>isaac_ros_image_proc</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
